### ISSUE TITLE
Request: iTerm2 colors

### ISSUE THREAD

**Issue by mamercad** [lamhoang1256/beautiful-dracula#1]
Thanks for the beautiful spin on Dracula, it's be sweet to have matching iTerm2 colors.

**Comment by lamhoang1256** [comment]
@mamercad Thank you for using my theme, unfortunately I am using windows and have never used iTerm2. So it might be a bit difficult for me to complete your request

**Comment by lamhoang1256** [comment]
@mamercad But I see there are a few extensions that support converting vscode themes to iterm2 you can refer to 
https://marketplace.visualstudio.com/items?itemName=tusaeff.vscode-iterm2-theme-sync
https://dev.to/abinavseelan/use-your-favorite-vscode-theme-on-iterm2-58gc

**Comment by mamercad** [comment]
> @mamercad But I see there are a few extensions that support converting vscode themes to iterm2 you can refer to https://marketplace.visualstudio.com/items?itemName=tusaeff.vscode-iterm2-theme-sync https://dev.to/abinavseelan/use-your-favorite-vscode-theme-on-iterm2-58gc

Ah thank you, I'll take a 👀
