### ISSUE TITLE
Highlight for keywords

### ISSUE THREAD

**Issue by Cahmoraes** [lamhoang1256/beautiful-dracula#2]
Access modifiers color the same as method names. It ends up getting a little confusing.
It would be nice if you could add a different color to challenge the modifiers: private, public and protected.

![image](https://user-images.githubusercontent.com/17452938/230747010-0b974cdc-8b42-4399-b5f7-aeec166136cf.png)

The same happens with keywords like extends, abstract and implements.

![image](https://user-images.githubusercontent.com/17452938/230747066-d389780e-d727-4a90-8cd8-1d6abef3803a.png)

![image](https://user-images.githubusercontent.com/17452938/230747043-0303861f-408b-4fbd-9621-ab73618238f6.png)

**Comment by lamhoang1256** [comment]
@Cahmoraes Hi man, i checked and yes it is a bit confusing using method modifes. And I also really want to change 2 different colors for **private** and **readonly** but vscode doesn't allow it. I also refer a few themes and found this to be a bug of vscode
Example: Atom One Dark Theme

![atom](https://user-images.githubusercontent.com/61537853/230754206-5d24e157-6f90-470a-80dc-3e886d277fc2.png)

And I've optimize the color of the method modifiers for better readability. If you want, you can try updating Beautiful dracula to the latest version to experience

![version-0.1.4](https://user-images.githubusercontent.com/61537853/230753096-447484ee-3f43-407b-b10c-7dc8a4427f2c.jpg)

**Comment by Cahmoraes** [comment]
f the text you provided into English: “Hello my friend! The result is very beautiful. Your theme is very good for productivity, congratulations on your work.

I updated it here in VS Code and only the keyword abstract did not change.

![image](https://user-images.githubusercontent.com/17452938/230774476-2ffe0f8f-3c9f-4f70-9f32-5b10cd41ce67.png)

**Comment by lamhoang1256** [comment]
@Cahmoraes  That's right bro, I looked at some other themes and realized it's the vscode keyword that doesn't allow to change

![1](https://user-images.githubusercontent.com/61537853/230775102-01408497-6e89-4676-b90b-35d2db89e313.png)
![2](https://user-images.githubusercontent.com/61537853/230775108-5f78513d-98f7-47c7-8ca3-966d39eadda5.png)
![3](https://user-images.githubusercontent.com/61537853/230775110-6051e60a-3888-4832-97b1-7da1fade0019.png)

**Comment by Cahmoraes** [comment]
Perfect my friend. Thanks a lot, still your theme is the best

**Comment by lamhoang1256** [comment]
Thank you very much for using the theme, wish you have the best coding experience with Beautiful Dracula ☺️
